package com.prolosys.rfid.common.constants;

public enum ConfigurationEnum {
	
//	PURCHASES_COST_LIMIT,
	
	PREFIX_CENTER,
	PREFIX_ZONE,
	PREFIX_WAREHOUSE,
	PREFIX_AREA,
	PREFIX_LOCATION,
	
	
	PREFIX_MATERIAL,
	PREFIX_VENDOR,
	PREFIX_CONSUMPTION,	//
	PREFIX_PURCHASEORDER, //Órdenes de compra
	PREFIX_STORATEUNIT,
	PREFIX_FIXEDASSET,
	
	PREFIX_PRODUCTIVEUNIT, // Casetas
	PREFIX_BATCH,
	PREFIX_ENTRYBATCH,
	PREFIX_OUTPUTBATCH,
	PREFIX_SERVICE,
	PREFIX_INVENTORY,
	
	PREFIX_CLIENT,
	
	WAREHOUSES_MAIN

	

	

	
//	DASHBOARDS_ENTRANCE_ALERT_A,
//	DASHBOARDS_ENTRANCE_ALERT_A_B,
//	DASHBOARDS_ENTRANCE_ALERT_B_C,
//	DASHBOARDS_ENTRANCE_HISTO_RANGE,
//	
////	DASHBOARDS_WAREHOUSE_ALERT_A,
//	DASHBOARDS_WAREHOUSE_ALERT_A_B,
//	DASHBOARDS_WAREHOUSE_ALERT_B_C,
//	
////	DASHBOARDS_DELIVERIES_ALERT_A,
//	DASHBOARDS_DELIVERIES_ALERT_A_B,
//	DASHBOARDS_DELIVERIES_ALERT_B_C,
//	DASHBOARDS_DELIVERIES_HISTO_RANGE,
//	
//	RFID_RSSI_TO_RECORD,
//	RFID_PREFIXES_TO_RECORD,
//	RFID_TIME_TO_RECORD,
//	
//	RFID_PREFIXES_UA,
//	RFID_PREFIXES_MTC;

}
